In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
raw_df = pd.read_csv('PSCompPars_2026.01.29_08.24.06.csv')

In [4]:
raw_df

,pl_name,hostname,pl_letter,hd_name,hip_name,tic_id,gaia_dr2_id,gaia_dr3_id,sy_snum,sy_pnum,...,sy_kepmagerr1,sy_kepmagerr2,sy_kepmag_reflink,pl_nnotes,st_nphot,st_nrvc,st_nspec,pl_nespec,pl_ntranspec,pl_ndispec
0,11 Com b,11 Com,b,HD 107383,HIP 60202,TIC 72437047,Gaia DR2 3946945413106333696,Gaia DR3 3946945413106333696,2,1,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,2,1,2,0,0,0,0
1,11 UMi b,11 UMi,b,HD 136726,HIP 74793,TIC 230061010,Gaia DR2 1696798367260229376,Gaia DR3 1696798367260229376,1,1,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,0,1,1,0,0,0,0
2,14 And b,14 And,b,HD 221345,HIP 116076,TIC 333225860,Gaia DR2 1920113512486282240,Gaia DR3 1920113512486282240,1,1,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,0,1,1,0,0,0,0
3,14 Her b,14 Her,b,HD 145675,HIP 79248,TIC 219483057,Gaia DR2 1385293808145621504,Gaia DR3 1385293808145621504,1,2,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,0,1,4,1,0,0,0
4,16 Cyg B b,16 Cyg B,b,HD 186427,HIP 96901,TIC 27533327,Gaia DR2 2135550755683407232,Gaia DR3 2135550755683407232,3,1,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,5,1,4,3,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6075,ups And b,ups And,b,HD 9826,HIP 7513,TIC 189576919,Gaia DR2 348020448377061376,Gaia DR3 348020482735930112,2,3,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,5,1,10,1,0,0,0
6076,ups And c,ups And,c,HD 9826,HIP 7513,TIC 189576919,Gaia DR2 348020448377061376,Gaia DR3 348020482735930112,2,3,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,5,1,10,1,0,0,0
6077,ups And d,ups And,d,HD 9826,HIP 7513,TIC 189576919,Gaia DR2 348020448377061376,Gaia DR3 348020482735930112,2,3,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,5,1,10,1,0,0,0
6078,ups Leo b,ups Leo,b,NaN,NaN,TIC 49430557,Gaia DR2 3794167001116433152,Gaia DR3 3794167001116704000,1,1,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,0,0,0,0,0,0,0
6079,xi Aql b,xi Aql,b,HD 188310,HIP 97938,TIC 375464367,Gaia DR2 4298361114750843904,Gaia DR3 4298361114753012992,1,1,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,1,1,1,0,0,0,0

---
For calulating ESI of exoplanets, I considered mass (M) and radius (R)

According to _Earth Similarity Index (ESI)_ on PHL (Planetary Habitability Laboratory) Website, 

**"...A mass-radius relationship can also be used for this conversion, but it is not usually necessary since it gives similar results within the interest values(i.e., close to ESI = 1.0)."**

So we assume **Radius (R) is approximatey equal to Cube Root of Mass (M)**  



---

In [5]:
esi_df = raw_df[['pl_name','pl_rade','pl_bmasse']]

In [6]:
esi_df.head()

      pl_name  pl_rade    pl_bmasse
0    11 Com b     12.2  4914.898486
1    11 UMi b     12.3  4684.814200
2    14 And b     13.1  1131.151301
3    14 Her b     12.6  2559.472162
4  16 Cyg B b     13.5   565.737400

In [7]:
esi_df[esi_df['pl_rade'].isnull() & esi_df['pl_bmasse'].isnull()]

             pl_name  pl_rade  pl_bmasse
1922  KIC 10001893 b      NaN        NaN
1923  KIC 10001893 c      NaN        NaN
1924  KIC 10001893 d      NaN        NaN
4882       LkCa 15 b      NaN        NaN
4883       LkCa 15 c      NaN        NaN
4923       MWC 758 c      NaN        NaN
5265      TOI-1634 c      NaN        NaN

**NOTE:** 

I dropped all records that do not have both Mass (M) and Radius (R) because the ESI Formula is computed using Radius (R), Density, Escape Velocity and Surface Temperature.

We can use stellar flux or other parameters instead of those missing, but I want to keep it traditional, hence dropped

In [8]:
#Checking if we have any null values for both radius and mass
esi_df[esi_df['pl_rade'].isnull() & esi_df['pl_bmasse'].isnull()]

             pl_name  pl_rade  pl_bmasse
1922  KIC 10001893 b      NaN        NaN
1923  KIC 10001893 c      NaN        NaN
1924  KIC 10001893 d      NaN        NaN
4882       LkCa 15 b      NaN        NaN
4883       LkCa 15 c      NaN        NaN
4923       MWC 758 c      NaN        NaN
5265      TOI-1634 c      NaN        NaN

In [9]:
esi_df = esi_df.dropna(subset=['pl_rade','pl_bmasse'], thresh=1)

In [14]:
esi_df

         pl_name  pl_rade    pl_bmasse
0       11 Com b     12.2  4914.898486
1       11 UMi b     12.3  4684.814200
2       14 And b     13.1  1131.151301
3       14 Her b     12.6  2559.472162
4     16 Cyg B b     13.5   565.737400
...          ...      ...          ...
6075   ups And b     14.0   218.531000
6076   ups And c     12.3  4443.241130
6077   ups And d     12.5  3257.741172
6078   ups Leo b     14.2   162.092488
6079    xi Aql b     13.4   616.904938

[6073 rows x 3 columns]

### Radius-Mass Relation
Since we are looking for exoplanets that are similar to Earth in structure, we do not want Gas-Giants or Sub-Neptunes, therefore we only consider exoplanets with 

*"Radius <= 1.6 Earth Radius - R <= 1.6R⊕"*

In [12]:
esi_df[esi_df['pl_rade']>1.6]

         pl_name  pl_rade    pl_bmasse
0       11 Com b     12.2  4914.898486
1       11 UMi b     12.3  4684.814200
2       14 And b     13.1  1131.151301
3       14 Her b     12.6  2559.472162
4     16 Cyg B b     13.5   565.737400
...          ...      ...          ...
6075   ups And b     14.0   218.531000
6076   ups And c     12.3  4443.241130
6077   ups And d     12.5  3257.741172
6078   ups Leo b     14.2   162.092488
6079    xi Aql b     13.4   616.904938

[4857 rows x 3 columns]

4857 Exoplanets do not come under Terrestrial Regime -> Drop these records

In [15]:
esi_df = esi_df[esi_df['pl_rade'] <= 1.6]

In [16]:
esi_df

        pl_name  pl_rade  pl_bmasse
56     AU Mic d    1.020      1.053
90    Barnard b    0.720      0.299
91    Barnard c    0.743      0.335
92    Barnard d    0.694      0.263
93    Barnard e    0.637      0.193
...         ...      ...        ...
6029   YZ Cet b    0.913      0.700
6030   YZ Cet c    1.050      1.140
6031   YZ Cet d    1.030      1.090
6072  tau Cet g    1.180      1.750
6073  tau Cet h    1.190      1.830

[1173 rows x 3 columns]

**NOTE:** Filtering was applied directly to the reported numerical radius values without rounding; therefore, minor differences in the final record count arose due to numerical precision.

In [ ]:
#The Radius-Mass Relation Definition
def radius_mass_relation(pl_rade, pl_bmasse):

Now that we have atleast Mass (M) or Radius (R), we can calculate Density, but since we cannot directly measure the surface temperature of exoplanets.

We will use **Equilibrium Temperature[K]** *(eqt for short), if any null values in eqt we will calulate it by using its:
* Star's Luminosity (L*) (if missing radius and Temperature of the star),
* planet's abledo,
* orbital distance from the star.

In [11]:
raw_df[raw_df['pl_eqt'].isna()]

,pl_name,hostname,pl_letter,hd_name,hip_name,tic_id,gaia_dr2_id,gaia_dr3_id,sy_snum,sy_pnum,...,sy_kepmagerr1,sy_kepmagerr2,sy_kepmag_reflink,pl_nnotes,st_nphot,st_nrvc,st_nspec,pl_nespec,pl_ntranspec,pl_ndispec
0,11 Com b,11 Com,b,HD 107383,HIP 60202,TIC 72437047,Gaia DR2 3946945413106333696,Gaia DR3 3946945413106333696,2,1,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,2,1,2,0,0,0,0
1,11 UMi b,11 UMi,b,HD 136726,HIP 74793,TIC 230061010,Gaia DR2 1696798367260229376,Gaia DR3 1696798367260229376,1,1,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,0,1,1,0,0,0,0
2,14 And b,14 And,b,HD 221345,HIP 116076,TIC 333225860,Gaia DR2 1920113512486282240,Gaia DR3 1920113512486282240,1,1,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,0,1,1,0,0,0,0
3,14 Her b,14 Her,b,HD 145675,HIP 79248,TIC 219483057,Gaia DR2 1385293808145621504,Gaia DR3 1385293808145621504,1,2,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,0,1,4,1,0,0,0
4,16 Cyg B b,16 Cyg B,b,HD 186427,HIP 96901,TIC 27533327,Gaia DR2 2135550755683407232,Gaia DR3 2135550755683407232,3,1,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,5,1,4,3,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6075,ups And b,ups And,b,HD 9826,HIP 7513,TIC 189576919,Gaia DR2 348020448377061376,Gaia DR3 348020482735930112,2,3,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,5,1,10,1,0,0,0
6076,ups And c,ups And,c,HD 9826,HIP 7513,TIC 189576919,Gaia DR2 348020448377061376,Gaia DR3 348020482735930112,2,3,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,5,1,10,1,0,0,0
6077,ups And d,ups And,d,HD 9826,HIP 7513,TIC 189576919,Gaia DR2 348020448377061376,Gaia DR3 348020482735930112,2,3,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,5,1,10,1,0,0,0
6078,ups Leo b,ups Leo,b,NaN,NaN,TIC 49430557,Gaia DR2 3794167001116433152,Gaia DR3 3794167001116704000,1,1,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,0,0,0,0,0,0,0
6079,xi Aql b,xi Aql,b,HD 188310,HIP 97938,TIC 375464367,Gaia DR2 4298361114750843904,Gaia DR3 4298361114753012992,1,1,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,1,1,1,0,0,0,0

Since it has so many Null values, 

Step 1: Calculate eqt

Reuired Parameters:
* Stellar Luminosity (st_lum),
* Stellar radius(st_rad) and temperature(st_teff) (in case Luminosity is a null value),
* Albedo (Not in dataset,therefore we assume it as 0.3),
* Orbital Distance from star(pl_orbper)
    
Step 2: Checking if we can calculate eqt, if not then drop those records

Step 3: Finding Escape velocity

---